homepage: "https://www.qubes-os.org/"
primary_contact: "jpo@vt.edu"
auto_ccs:
 - "joanna@invisiblethingslab.com"
 - "marmarek@invisiblethingslab.com"
 - "paras.chetal@gmail.com"
architectures:
  - x86_64
  - i386
