homepage: "https://tukaani.org/xz/"
primary_contact: "lasse.collin@tukaani.org"
auto_ccs:
  - "bshas3@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
