{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha01.aar",
          "url": "navigation-ui-ktx-2.4.0-alpha01.aar",
          "size": 32267,
          "sha512": "b2a012738911fa301ce8cb761e1d57e7efcf827293a8aae5db22dd666505f730614c8de0443fc266afec6339dcb7f12db4ae7746254a81ccecb82c0112f504be",
          "sha256": "49c4210b82a54602e0528da0f74e235c82575b100ab9cebb2696f57b4dc948f6",
          "sha1": "eaa3ae23f8e6e197a6e22d61603eebc2ea8b842e",
          "md5": "fc02f91fcc197e07622792d840780830"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha01.aar",
          "url": "navigation-ui-ktx-2.4.0-alpha01.aar",
          "size": 32267,
          "sha512": "b2a012738911fa301ce8cb761e1d57e7efcf827293a8aae5db22dd666505f730614c8de0443fc266afec6339dcb7f12db4ae7746254a81ccecb82c0112f504be",
          "sha256": "49c4210b82a54602e0528da0f74e235c82575b100ab9cebb2696f57b4dc948f6",
          "sha1": "eaa3ae23f8e6e197a6e22d61603eebc2ea8b842e",
          "md5": "fc02f91fcc197e07622792d840780830"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha01-sources.jar",
          "url": "navigation-ui-ktx-2.4.0-alpha01-sources.jar",
          "size": 8751,
          "sha512": "0d56d35c76ca24964807607764080077f0d8ce960dc61e14629a2a1d50bd424ab455be041d64dc17edc52511c0db4d25c3e7b359a5bb44c9c37f2e0934ea1685",
          "sha256": "dc293a071dc2f04f69d456de6734531fa52ae69fecc83a4e1812006a3e5e3eae",
          "sha1": "407dd936012d5b65b0af3e897ea62e436a811419",
          "md5": "e5ff0652316f70fa6f7263ce5094a7ba"
        }
      ]
    }
  ]
}
