{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.leanback",
    "module": "leanback-preference",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.leanback",
          "module": "leanback",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "leanback-preference-1.1.0-alpha04.aar",
          "url": "leanback-preference-1.1.0-alpha04.aar",
          "size": 80384,
          "sha512": "c0080ed955366cabb6de9eb6ec686ada755a77858bdee91ae937df616740a314a17149ae10938b696ff1a1784901d26ed7c00652f9e4264d64c7eb80172c52a7",
          "sha256": "f57b9909d71237f49069cd734f7f1c503934df9e7801a5e9d7b9f6719f8a5f57",
          "sha1": "63f16c61493bfc8c60f96f384640924033c534a6",
          "md5": "6988b5273a835a5a113f92d5064e1972"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.leanback",
          "module": "leanback",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "leanback-preference-1.1.0-alpha04.aar",
          "url": "leanback-preference-1.1.0-alpha04.aar",
          "size": 80384,
          "sha512": "c0080ed955366cabb6de9eb6ec686ada755a77858bdee91ae937df616740a314a17149ae10938b696ff1a1784901d26ed7c00652f9e4264d64c7eb80172c52a7",
          "sha256": "f57b9909d71237f49069cd734f7f1c503934df9e7801a5e9d7b9f6719f8a5f57",
          "sha1": "63f16c61493bfc8c60f96f384640924033c534a6",
          "md5": "6988b5273a835a5a113f92d5064e1972"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "leanback-preference-1.1.0-alpha04-sources.jar",
          "url": "leanback-preference-1.1.0-alpha04-sources.jar",
          "size": 25995,
          "sha512": "070df014a7a76d257da5e587d1da1df7567ce9099a540d24f6ba92cd0bed7edf7afa46bdab34c0b901743014e50fe7ac80564082ca2942293c3f00823860423c",
          "sha256": "ae172655abe428bf2d09f5be202b796fff600a33f4942f9c3896cf259db25212",
          "sha1": "bdf52011dfa9d7fff646adb09730352d81fe4da4",
          "md5": "183fc81b472267ba4028ee3d7fa6f177"
        }
      ]
    }
  ]
}
