homepage: "https://python-pillow.org/"
primary_contact: "guidovranken@gmail.com"
auto_ccs:
 - "security@python-pillow.org"
sanitizers:
 - address
 - undefined
architectures:
 - x86_64
fuzzing_engines:
  - libfuzzer
