homepage: "https://github.com/guidovranken/bignum-fuzzer"
primary_contact: "guidovranken@gmail.com"
auto_ccs:
    - "martin.swende@ethereum.org"
    - "cdetrio@ethereum.org"
    - "openssl-security@openssl.org"
    - "kurt@roeckx.be"
    - "caswell.matt@googlemail.com"
    - "jz.maddock@gmail.com"
    - "jz.maddock@googlemail.com"
    - "agl@google.com"
    - "davidben@google.com"
    - "svaldez@google.com"
    - "support-mbedtls@arm.com"
    - "libmpdec@gmail.com"
    - "richard@levitte.org"
