language: rust

script:
  - cargo test

matrix:
  include:
    - rust: nightly
    - rust: beta
      env: RUSTFLAGS='--cfg remain_stable_testing'
    - rust: stable
      env: RUSTFLAGS='--cfg remain_stable_testing'
    - rust: 1.31.0
      env: RUSTFLAGS='--cfg remain_stable_testing'
