{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji-appcompat",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha01.aar",
          "url": "emoji-appcompat-1.2.0-alpha01.aar",
          "size": 15521,
          "sha512": "b9528e452fc049167061ad070934f6aec68d16a05d58c2162ab7071bfbce5449d749bb8bbe59cbc0d5f8c8291a1cd606b9ab9360b2eda4c2e548d2bb9a85b162",
          "sha256": "e66a724a50ca8360f61fe62df099fd365286fc2784587a10575c1f29e3405a26",
          "sha1": "08c607697ed083694f2b4fefe59ac4671e523341",
          "md5": "7b3cfda334ccc2143b0fa1b8335f1793"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha01.aar",
          "url": "emoji-appcompat-1.2.0-alpha01.aar",
          "size": 15521,
          "sha512": "b9528e452fc049167061ad070934f6aec68d16a05d58c2162ab7071bfbce5449d749bb8bbe59cbc0d5f8c8291a1cd606b9ab9360b2eda4c2e548d2bb9a85b162",
          "sha256": "e66a724a50ca8360f61fe62df099fd365286fc2784587a10575c1f29e3405a26",
          "sha1": "08c607697ed083694f2b4fefe59ac4671e523341",
          "md5": "7b3cfda334ccc2143b0fa1b8335f1793"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha01-sources.jar",
          "url": "emoji-appcompat-1.2.0-alpha01-sources.jar",
          "size": 4355,
          "sha512": "05730b58fb8391f28050b8cc51cfb42fdfc6c888cbb70b642d1e8b11f82b15946b65f05350de21d4f222e58f2e2d97ed4e195facd843c06552b784e7c4edd8ec",
          "sha256": "8c37ea1aefdd5d8e36d6fd5d7535c6fdfadd02b61fa51c1e4178b0cec49e6de0",
          "sha1": "6100352f9c99794e5ec330e4e428e344a7b3a245",
          "md5": "d708308a2084b09201efe840d9541b78"
        }
      ]
    }
  ]
}
