dist: xenial

language: c

arch:
  - amd64
  - ppc64le

compiler:
  - gcc

env:
  global:
    - CODECOV_TOKEN="040ce7eb-5bc7-4040-8324-364f3ef4baa3"
    - CFLAGS="-coverage"
  matrix:
    - CONFIGURE_ARGS=-fHNPSOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-bfHNPSOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-dfHNPSOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-fEHNPSOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-bfEHNPSOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-dfEHNPSOg GEN_HOST=1 LONG_BIT=64
    - CONFIGURE_ARGS=-fHNPSOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-bfHNPSOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-dfHNPSOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-fEHNPSOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-bfEHNPSOg GEN_HOST=1 LONG_BIT=32
    - CONFIGURE_ARGS=-dfEHNPSOg GEN_HOST=1 LONG_BIT=32

before_install:
  - sudo apt-get install -y dc
  - pip install --user codecov

before_script:
  - curl -o tests/bc/scripts/timeconst.bc https://raw.githubusercontent.com/torvalds/linux/master/kernel/time/timeconst.bc

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./configure.sh "$CONFIGURE_ARGS" && make -j4 && make -j4 test ; fi
