/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rockchip_graphics_SaveBaseParameterUtil */

#ifndef _Included_com_rockchip_graphics_SaveBaseParameterUtil
#define _Included_com_rockchip_graphics_SaveBaseParameterUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rockchip_graphics_SaveBaseParameterUtil
 * Method:    outputImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rockchip_graphics_SaveBaseParameterUtil_outputImage
  (JNIEnv * env, jclass clazz, jstring path);

#ifdef __cplusplus
}
#endif
#endif
