homepage: "https://libexif.github.io"
primary_contact: "dan@coneharvesters.com"
auto_ccs:
  - paul.l.kehrer@gmail.com
  - marcus@jet.franken.de
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
