homepage: "http://www.automatak.com/opendnp3/"
primary_contact: "info@automatak.com"
auto_ccs :
  - "p.antoine@catenacyber.fr"
  - "emile@automatak.com"

sanitizers:
  - address
  - memory
  - undefined
