homepage: "https://hg.mozilla.org/mozilla-central/file/tip/gfx/qcms/"
primary_contact: "twsmith@mozilla.com"
sanitizers:
- address
- undefined
- memory
auto_ccs:
- "aosmond@mozilla.com"
- "jmuizelaar@mozilla.com"
- "cdiehl@mozilla.com"
