sudo: false

branches:
  except:
    - debian
    - khronos-registry

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

language:
  - c

services:
  - docker

matrix:
  exclude:
  - os: osx
    compiler: gcc

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install python@3 meson
      # Use a Ninja with QuLogic's patch: https://github.com/ninja-build/ninja/issues/1219
      mkdir -p $HOME/tools; curl -L http://nirbheek.in/files/binaries/ninja/macos/ninja -o $HOME/tools/ninja; chmod +x $HOME/tools/ninja
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ebassi/epoxyci ; fi

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo FROM ebassi/epoxyci > Dockerfile
      echo ADD . /root >> Dockerfile
      echo WORKDIR /root >> Dockerfile
      docker build -t withgit .
    fi

env:
  - BUILD_OPTS=""
  - BUILD_OPTS="-Dglx=no"
  - BUILD_OPTS="-Degl=no"
  - BUILD_OPTS="-Dx11=false"

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run withgit /bin/sh -c "CC=$CC .travis/epoxy-ci-linux.sh $BUILD_OPTS" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /bin/sh -c "CC=$CC .travis/epoxy-ci-osx.sh $BUILD_OPTS" ; fi
