homepage: "https://chromium.googlesource.com/chromiumos/third_party/tpm2"
# todo: delete Dockerfile from tpm2 repo.
# Docker files change too much, it was moved to oss-fuzz repository.
#
#dockerfile:
#  git: "https://chromium.googlesource.com/chromiumos/third_party/tpm2/"
#  path: "fuzz/Dockerfile"
primary_contact: "ngm@google.com"
auto_ccs:
  - "tpm-security-bugs@google.com"
  - "dkrahn@google.com"
  - "vbendeb@google.com"
  - "apronin@google.com"
  - "cfir@google.com"
  - "mruthven@google.com"
