homepage: "https://github.com/h2o/picotls"
primary_contact: "jonathan.foote@gmail.com"
auto_ccs:
  - "frederik.deweerdt@gmail.com"
  - "kazuhooku@gmail.com"
  - "i.nagata110@gmail.com"
  - "tmaesaka@gmail.com"
  - "security@fastly.com"
