homepage: "https://gdal.org"
primary_contact: "even.rouault@gmail.com"
auto_ccs:
  - "schwehr@gmail.com"
  - "mateusz@loskot.net"
  - "bishop.dev@gmail.com"
  - "juergen.fischer@gmail.com"
  - "athomas@thinkspatial.com.au"
  - "ari.jolma@gmail.com"
  - "bjorn.harrtell@gmail.com"
architectures:
  - x86_64
  - i386
