{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.5.0-alpha01.aar",
          "url": "core-ktx-1.5.0-alpha01.aar",
          "size": 164712,
          "sha512": "73f14f3bfc52384e3a21715b5288695b40d04752870ec2255117fa864b0a951965976cbab99852d8b78a89d905a0890642de5fe5c88725ac579d905e0db1abee",
          "sha256": "c6e7bb597fab26592275d5d99237b0d95a66d963f0be8eec522f3a4851712e3e",
          "sha1": "9240eb25212603c6cf2a2b5262bd35e66d97062d",
          "md5": "acd6ada23ec546a2a9c6631aaf49a736"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.5.0-alpha01.aar",
          "url": "core-ktx-1.5.0-alpha01.aar",
          "size": 164712,
          "sha512": "73f14f3bfc52384e3a21715b5288695b40d04752870ec2255117fa864b0a951965976cbab99852d8b78a89d905a0890642de5fe5c88725ac579d905e0db1abee",
          "sha256": "c6e7bb597fab26592275d5d99237b0d95a66d963f0be8eec522f3a4851712e3e",
          "sha1": "9240eb25212603c6cf2a2b5262bd35e66d97062d",
          "md5": "acd6ada23ec546a2a9c6631aaf49a736"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.5.0-alpha01-sources.jar",
          "url": "core-ktx-1.5.0-alpha01-sources.jar",
          "size": 61417,
          "sha512": "b2d38ec86f29efe1b4d7850a6a31a3b61be9d6f587dfddd64fcbf9c00563b204985c6fd50cf1d60c326b6d1db966acf8b10a7168ee4fe916c1006deadb5dacf7",
          "sha256": "e00b30caea68e22c293844fcad395afe6ea6caaf088ae28d56940f7c9fa90296",
          "sha1": "87d6ce6074d4d0f120b4796effe5fa75511adb88",
          "md5": "60e58062c6d90b40963f6d2cf5504442"
        }
      ]
    }
  ]
}
