{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-ktx",
    "version": "2.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-alpha05.aar",
          "url": "lifecycle-runtime-ktx-2.3.0-alpha05.aar",
          "size": 42513,
          "sha512": "036b0cbabf8530b0587c49decb5758a363d5204689fba14941898235ed82bcd25295c67cfaffe44704767b8dc73df7c01802f1a0e6b3f937615837fd82ffaebd",
          "sha256": "afad8e644d53fc9dab80204deebcbfe5f8641df40394bd878ce68b79b0cc0aa8",
          "sha1": "b381c66ad7e8c2d22666e3274dcae8329bde1f10",
          "md5": "2f0503035dd8d6c26c738d6195e0c5af"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-alpha05.aar",
          "url": "lifecycle-runtime-ktx-2.3.0-alpha05.aar",
          "size": 42513,
          "sha512": "036b0cbabf8530b0587c49decb5758a363d5204689fba14941898235ed82bcd25295c67cfaffe44704767b8dc73df7c01802f1a0e6b3f937615837fd82ffaebd",
          "sha256": "afad8e644d53fc9dab80204deebcbfe5f8641df40394bd878ce68b79b0cc0aa8",
          "sha1": "b381c66ad7e8c2d22666e3274dcae8329bde1f10",
          "md5": "2f0503035dd8d6c26c738d6195e0c5af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-ktx-2.3.0-alpha05-sources.jar",
          "url": "lifecycle-runtime-ktx-2.3.0-alpha05-sources.jar",
          "size": 8290,
          "sha512": "d0a232c31e1256a7591a3f179314297d4d25696e5cd9dca926aee0a6c6e47b825f06f3953c5935e9b6b77623ca91331615971df2b7d2fc59a0b802bc5988fca7",
          "sha256": "caf1119a13b148e5b5225e487956104f9832b4919061823e5f1d8a6c8eac3158",
          "sha1": "9ee179ce9a5a85cc9d93ab052bc96464deb452bf",
          "md5": "d6044ccf258952a4a1099ad769b38fd3"
        }
      ]
    }
  ]
}
