{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.3.0-alpha05.aar",
          "url": "lifecycle-process-2.3.0-alpha05.aar",
          "size": 8445,
          "sha512": "a6a6d3378195302857031448e292acd3e0cf46f46ff51117ae4a3f6af90edcbdcce8ae4b9e217d606522133cb999f950d071921e1bdb2c098f59f2a45bb658c7",
          "sha256": "4cc79ce65a02a145b2aacebff0c83122bd7b391ca38cdf22485cd1dc489bb72d",
          "sha1": "a8ce90d4b8611779239f1319312122c86080f4f6",
          "md5": "6068b23f3d518ca1bc9da9143c892c45"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.3.0-alpha05.aar",
          "url": "lifecycle-process-2.3.0-alpha05.aar",
          "size": 8445,
          "sha512": "a6a6d3378195302857031448e292acd3e0cf46f46ff51117ae4a3f6af90edcbdcce8ae4b9e217d606522133cb999f950d071921e1bdb2c098f59f2a45bb658c7",
          "sha256": "4cc79ce65a02a145b2aacebff0c83122bd7b391ca38cdf22485cd1dc489bb72d",
          "sha1": "a8ce90d4b8611779239f1319312122c86080f4f6",
          "md5": "6068b23f3d518ca1bc9da9143c892c45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.3.0-alpha05-sources.jar",
          "url": "lifecycle-process-2.3.0-alpha05-sources.jar",
          "size": 5779,
          "sha512": "8b0aebfa4a7182c1b8cd1aa6c2aeaa7d6f87fe0612bcafd186bf992ae55d0bfe9e7e716e00da6976b2a7e50477cdbc126186dbdd9a5339b2a380f0eb44efbfdb",
          "sha256": "34247e6a4c63d14f59c37f0e1780f0b64329e52316f22b53c9a6e0975db030dd",
          "sha1": "47344d875a6f6b0db710194fc03b511ddc8b13cf",
          "md5": "3a273ea3c91f35168e08dd4540ac309b"
        }
      ]
    }
  ]
}
