{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotation-1.2.0-alpha02.jar",
          "url": "annotation-1.2.0-alpha02.jar",
          "size": 29110,
          "sha512": "e82b44f646d226b74d49c7c9340597e21df40a35d3c7f391a4667c5b6d1aec497d7aa38430842dc7c88411765206830128e919c724ce49355e2de047258848ee",
          "sha256": "d872cf824227017565444d5aa0073a45b33bc641650a74a09cea3ca05cfc7774",
          "sha1": "cf0f760ea00702c040b3f8c9ccbe615ae26356dc",
          "md5": "12a9e886204e3aef3172f7d3cf8c4db7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-1.2.0-alpha02.jar",
          "url": "annotation-1.2.0-alpha02.jar",
          "size": 29110,
          "sha512": "e82b44f646d226b74d49c7c9340597e21df40a35d3c7f391a4667c5b6d1aec497d7aa38430842dc7c88411765206830128e919c724ce49355e2de047258848ee",
          "sha256": "d872cf824227017565444d5aa0073a45b33bc641650a74a09cea3ca05cfc7774",
          "sha1": "cf0f760ea00702c040b3f8c9ccbe615ae26356dc",
          "md5": "12a9e886204e3aef3172f7d3cf8c4db7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-1.2.0-alpha02-sources.jar",
          "url": "annotation-1.2.0-alpha02-sources.jar",
          "size": 53829,
          "sha512": "1898d88319213ccbda9369ced541b62c231894b6c540572ea35ff96c53c4d2179ad4b3d092c7f85806a95dbdcef4d42c3961548f96f90bbbd66bab0ed91dd306",
          "sha256": "e161e7a3618067862d5d3250c52f56cd3b2a81e1d52e49dbe660aa397ae17781",
          "sha1": "df9acce4eab41184c6ad166b55f36a753d2b5de0",
          "md5": "9e6395da7520fbc6634fbd1fa705d04b"
        }
      ]
    }
  ]
}
