[package]
name = "wire_format_derive"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
proc-macro2 = "=0.4"
quote = "=0.6"
syn = "=0.15"

[lib]
proc-macro = true
path = "wire_format_derive.rs"
