homepage: "https://github.com/nemtech/catapult-server"
primary_contact: "wayonb@gmail.com"
auto_ccs:
  - "gimer.outer.space@gmail.com"
  - "jaguar5pow4@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
