{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.3.0-alpha05.aar",
          "url": "lifecycle-livedata-core-2.3.0-alpha05.aar",
          "size": 8644,
          "sha512": "29e663dd8b0388a994be48198f3711533dd50c12461172766b62901223734b91d701c98cd2377318fa8a9ee3a5ff2dae73e24bea2e2958c5cc97613a93dd1c64",
          "sha256": "2a9363cb70663f5bd7b8870f040358d4cf67857d3e0eb3bdbb7aaed333ee5de5",
          "sha1": "68ccff1f1680bbc6f333dc227229dd869862c0ad",
          "md5": "be8ad282aa8d3bb1c184b61946878c87"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.3.0-alpha05.aar",
          "url": "lifecycle-livedata-core-2.3.0-alpha05.aar",
          "size": 8644,
          "sha512": "29e663dd8b0388a994be48198f3711533dd50c12461172766b62901223734b91d701c98cd2377318fa8a9ee3a5ff2dae73e24bea2e2958c5cc97613a93dd1c64",
          "sha256": "2a9363cb70663f5bd7b8870f040358d4cf67857d3e0eb3bdbb7aaed333ee5de5",
          "sha1": "68ccff1f1680bbc6f333dc227229dd869862c0ad",
          "md5": "be8ad282aa8d3bb1c184b61946878c87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.3.0-alpha05-sources.jar",
          "url": "lifecycle-livedata-core-2.3.0-alpha05-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
