homepage: "https://xiph.org/vorbis/"
primary_contact: "daede003@umn.edu"
auto_ccs:
  - paul.l.kehrer@gmail.com
  - alex.gaynor@gmail.com
vendor_ccs:
  - cdiehl@mozilla.com
  - twsmith@mozilla.com
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
