[package]
name = "data_model"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
assertions = { path = "../assertions" } # provided by ebuild

[workspace]
