homepage: "https://github.com/harfbuzz/harfbuzz"
primary_contact: "harfbuzz-admin@googlegroups.com"
auto_ccs:
  - "behdad.esfahbod@gmail.com"
  - "behdad@google.com"
  - "ebrahim@gnu.org"
  - "ebraminio@gmail.com"
  - "grieger@google.com"
  - "rsheeter@google.com"
  - "dr.khaled.hosny@gmail.com"
  - "jfkthame@gmail.com"
  - "cchapman@adobe.com"
  - "ariza@typekit.com"
  - "qxliu@google.com"
  - "ckitagawa@google.com"
vendor_ccs:
  - "jmuizelaar@mozilla.com"
  - "lsalzman@mozilla.com"
  - "twsmith@mozilla.com"
fuzzing_engines:
 - libfuzzer
 - afl
 - honggfuzz
 - dataflow
sanitizers:
 - address
 - undefined
 - memory
 - dataflow
architectures:
  - x86_64
  - i386
