my_robolectric_runtime_deps := \
    lib/accessibility-test-framework-2.1.jar \
    lib/animal-sniffer-annotations-1.17.jar \
    lib/annotation-1.0.0.jar \
    lib/annotations-4.3.1.jar \
    lib/asm-6.0.jar \
    lib/asm-commons-6.0.jar \
    lib/asm-tree-6.0.jar \
    lib/asm-util-6.0.jar \
    lib/auto-common-0.8.jar \
    lib/auto-service-1.0-rc4.jar \
    lib/bcprov-jdk15on-1.52.jar \
    lib/checker-qual-2.5.2.jar \
    lib/commons-codec-1.3.jar \
    lib/commons-logging-1.1.1.jar \
    lib/error_prone_annotations-2.2.0.jar \
    lib/failureaccess-1.0.1.jar \
    lib/guava-27.0.1-jre.jar \
    lib/hamcrest-core-1.3.jar \
    lib/hamcrest-library-1.3.jar \
    lib/httpclient-4.0.3.jar \
    lib/httpcore-4.0.1.jar \
    lib/icu4j-53.1.jar \
    lib/j2objc-annotations-1.1.jar \
    lib/javax.annotation-api-1.3.2.jar \
    lib/javax.inject-1.jar \
    lib/jsr305-3.0.2.jar \
    lib/junit-4.3.1.jar \
    lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar \
    lib/monitor-1.2.0.aar \
    lib/pluginapi-4.3.1.jar \
    lib/plugins-maven-dependency-resolver-4.3.1.jar \
    lib/protobuf-java-2.6.1.jar \
    lib/resources-4.3.1.jar \
    lib/robolectric-4.3.1.jar \
    lib/sandbox-4.3.1.jar \
    lib/shadowapi-4.3.1.jar \
    lib/shadows-framework-4.3.1.jar \
    lib/shadows-httpclient-4.3.1.jar \
    lib/shadows-multidex-4.3.1.jar \
    lib/shadows-playservices-4.3.1.jar \
    lib/shadows-supportv4-4.3.1.jar \
    lib/sqlite4java-0.282.jar \
    lib/support-annotations-28.0.0.jar \
    lib/utils-4.3.1.jar \
    lib/utils-reflector-4.3.1.jar \
    lib/vtd-xml-2.11.jar 
