{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-alpha05.aar",
          "url": "lifecycle-livedata-ktx-2.3.0-alpha05.aar",
          "size": 40508,
          "sha512": "141d5c608e53d0bc39e898bd91dbac053c209d88ee1a3c51e913508e8ce4ab7daa00a361bff995b841319e70cc95dee9a5e04230b42bbc78aaecc8ae4f6ca9b8",
          "sha256": "3241ed413d8ac6b5c387ea32fd1a1d9a7c01e14efaf7bbda453227d43c610195",
          "sha1": "3666475da6b6bf764dcc0c6fa6056cde92faf532",
          "md5": "cd846732110b823b174f34f277f097e8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-alpha05.aar",
          "url": "lifecycle-livedata-ktx-2.3.0-alpha05.aar",
          "size": 40508,
          "sha512": "141d5c608e53d0bc39e898bd91dbac053c209d88ee1a3c51e913508e8ce4ab7daa00a361bff995b841319e70cc95dee9a5e04230b42bbc78aaecc8ae4f6ca9b8",
          "sha256": "3241ed413d8ac6b5c387ea32fd1a1d9a7c01e14efaf7bbda453227d43c610195",
          "sha1": "3666475da6b6bf764dcc0c6fa6056cde92faf532",
          "md5": "cd846732110b823b174f34f277f097e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.3.0-alpha05-sources.jar",
          "url": "lifecycle-livedata-ktx-2.3.0-alpha05-sources.jar",
          "size": 8201,
          "sha512": "1607196926547b6c2e33590d8d9a4048fd343049bdfc736e643bb7e8f083462e2a02fecd16c2a4c924b793b22811a98dd76869ef6ec804cbaaaee607189292b6",
          "sha256": "41aa31144a473c4025d6cf5f55eb68c109399c806e9772c6d00bfb9c5e149ef2",
          "sha1": "3e104f0a8f35e9a17c5b6bc2ccc8450bec99a2e9",
          "md5": "d73a2d79278c9c357fabbd0f7ad7e646"
        }
      ]
    }
  ]
}
