homepage: "https://perfetto.dev"
primary_contact: "fmayer@google.com"
auto_ccs:
  - "hjd@google.com"
  - "lalitm@google.com"
  - "perfetto-oss-fuzz@google.com"
  - "primiano@google.com"
  - "rsavitski@google.com"
  - "taylori@google.com"
vendor_ccs:
  - bcreasey@google.com
  - hamzeh@google.com
  - geuteneier@google.com
  - hollyhall@google.com
  - mikelogan@google.com
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
