homepage: "https://sqlite.org/"
primary_contact: "drhsqlite@gmail.com"
auto_ccs:
  - "sboydps@gmail.com"
  - "cdiehl@mozilla.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
