language: python
dist: xenial

services:
  - docker

before_install:
  - git fetch origin +refs/heads/$TRAVIS_BRANCH

install:
  - pip install -r infra/travis/requirements.txt

matrix:
  include:
    - name: "presubmit"
      install:
        - pip install -r infra/dev-requirements.txt
      script: ./infra/presubmit.py
    - name: "libfuzzer address x86_64"
      env:
        - TRAVIS_ENGINE=libfuzzer
        - TRAVIS_SANITIZER=address
        - TRAVIS_ARCHITECTURE=x86_64
    - name: "libfuzzer memory x86_64"
      env:
        - TRAVIS_ENGINE=libfuzzer
        - TRAVIS_SANITIZER=memory
        - TRAVIS_ARCHITECTURE=x86_64
    - name: "libfuzzer undefined x86_64"
      env:
        - TRAVIS_SANITIZER=undefined
        - TRAVIS_ENGINE=libfuzzer
        - TRAVIS_ARCHITECTURE=x86_64
    - name: "afl address x86_64"
      env:
        - TRAVIS_ENGINE=afl
        - TRAVIS_SANITIZER=address
        - TRAVIS_ARCHITECTURE=x86_64
    - name: "none address x86_64"
      env:
        - TRAVIS_ENGINE=none
        - TRAVIS_SANITIZER=address
        - TRAVIS_ARCHITECTURE=x86_64
    - name: "libfuzzer address i386"
      env:
        - TRAVIS_ENGINE=libfuzzer
        - TRAVIS_SANITIZER=address
        - TRAVIS_ARCHITECTURE=i386
    - name: "dataflow dataflow x86_64"
      env:
        - TRAVIS_ENGINE=dataflow
        - TRAVIS_SANITIZER=dataflow
        - TRAVIS_ARCHITECTURE=x86_64

script: ./infra/travis/travis_build.py

notifications:
  webhooks: https://www.travisbuddy.com/
