homepage: "https://github.com/khaledhosny/ots"
primary_contact: "dr.khaled.hosny@gmail.com"
auto_ccs:
  - "kevin899@gmail.com"
  - "jfkthame@gmail.com"
vendor_ccs:
  - "jmuizelaar@mozilla.com"
  - "lsalzman@mozilla.com"
  - "twsmith@mozilla.com"
