{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.slice",
    "module": "slice-core",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-core-1.1.0-alpha02.aar",
          "url": "slice-core-1.1.0-alpha02.aar",
          "size": 172768,
          "sha512": "7fa18ff9ae778ef324d88dc5f2f87a8a1db17b93e65aadb53ff88eac631d0e142346794be8e0936115b1e86dbf4e59b59e74ce5542e640f7a4ec997fcfd605d4",
          "sha256": "0cde4943942a05025d8103c7dc6bb64ce1ac84d13c8c898d7c51a4f4669b2bee",
          "sha1": "e8df276e371a35500b449b90b909ce87bb3bb698",
          "md5": "907d2d1d8dfad4c1593cffb04f69cf5c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-core-1.1.0-alpha02.aar",
          "url": "slice-core-1.1.0-alpha02.aar",
          "size": 172768,
          "sha512": "7fa18ff9ae778ef324d88dc5f2f87a8a1db17b93e65aadb53ff88eac631d0e142346794be8e0936115b1e86dbf4e59b59e74ce5542e640f7a4ec997fcfd605d4",
          "sha256": "0cde4943942a05025d8103c7dc6bb64ce1ac84d13c8c898d7c51a4f4669b2bee",
          "sha1": "e8df276e371a35500b449b90b909ce87bb3bb698",
          "md5": "907d2d1d8dfad4c1593cffb04f69cf5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slice-core-1.1.0-alpha02-sources.jar",
          "url": "slice-core-1.1.0-alpha02-sources.jar",
          "size": 51108,
          "sha512": "d7950bad9f0a9a74664fe472ee8828e3f7582c99f24fecd49705795174107381d362012f393d5ea8c5f876a3f603b7b130eea0bc8c57aecc8104c1cebdc6a18c",
          "sha256": "d42a9533d96bda8abc215cec96c74c966dcd4c8bf667e6f8638bfee19ddcb00b",
          "sha1": "1f4645da1c658d9331365300d4e44ed3d555331b",
          "md5": "cfee6a7ca5b55ba471f914a44fd0b080"
        }
      ]
    }
  ]
}
