homepage: "https://www.theora.org/"
primary_contact: "guidovranken@gmail.com"
vendor_ccs:
 - "cdiehl@mozilla.com"
 - "daede003@umn.edu"
 - "twsmith@mozilla.com"
sanitizers:
 - address
 - undefined
 - memory
 - dataflow
architectures:
 - x86_64
 - i386
