homepage: https://github.com/brianmario/yajl-ruby
primary_contact: seniorlopez@gmail.com
sanitizers:
  - address
  - undefined
  - memory
auto_ccs:
  - aaron.patterson@gmail.com
  - jonathan@titanous.com
