apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  type: NodePort
  selector:
    app: jenkins-master
  ports:
  - name: agent
    port: 50000
  - name: http
    port: 8080
    targetPort: 8080
