homepage: "http://www.openvswitch.org"
primary_contact: "blp@ovn.org"
auto_ccs:
  - "jpettit@ovn.org"
  - "pfaffben@gmail.com" 
  - "pkusunyifeng@gmail.com"
  - "bshas3@gmail.com"
  - "cpp.code.lv@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
