{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-common-java8",
    "version": "2.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-java8-2.3.0-alpha05.jar",
          "url": "lifecycle-common-java8-2.3.0-alpha05.jar",
          "size": 1015,
          "sha512": "4f8f9ce47803c9724075978f7f046fb067198251e1923d4d47e27a5a9f50b76aa0696af423de13c97f09c4b3214f567c4bf4b1025354b231fd5ef8e56787ffe9",
          "sha256": "a1ec63c1bb973443cb731d78ec336c5e20e7ee35c89cbb32d36f92c55bb02542",
          "sha1": "cd3478503da69b1a7e0319bd2d1389943db9b364",
          "md5": "6e0e3c087148a1ad689b4173b8f5af5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-java8-2.3.0-alpha05.jar",
          "url": "lifecycle-common-java8-2.3.0-alpha05.jar",
          "size": 1015,
          "sha512": "4f8f9ce47803c9724075978f7f046fb067198251e1923d4d47e27a5a9f50b76aa0696af423de13c97f09c4b3214f567c4bf4b1025354b231fd5ef8e56787ffe9",
          "sha256": "a1ec63c1bb973443cb731d78ec336c5e20e7ee35c89cbb32d36f92c55bb02542",
          "sha1": "cd3478503da69b1a7e0319bd2d1389943db9b364",
          "md5": "6e0e3c087148a1ad689b4173b8f5af5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-common-java8-2.3.0-alpha05-sources.jar",
          "url": "lifecycle-common-java8-2.3.0-alpha05-sources.jar",
          "size": 1612,
          "sha512": "570946e3208e5c5092e79f75530f82230e88c9b593177665eea6524928bbe5f5ad33efa0456584f333cf9145af3759e8b6e53f874a9f1107198110f6af08652c",
          "sha256": "f6dc13cca0d461dd9ac0c515ede93b45f2209545cb75e658040ae7df5dc80823",
          "sha1": "777ad8a2c39ec412a8c77a3923ceb536946acb29",
          "md5": "9033c02e94f794b2f605cec8231db2c8"
        }
      ]
    }
  ]
}
