homepage: "https://github.com/libjpeg-turbo/libjpeg-turbo"
vendor_ccs:
  - "aosmond@mozilla.com"
  - "tnikkel@mozilla.com"
  - "twsmith@mozilla.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
