[package]
name = "sys_util"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
data_model = { path = "../data_model" } # provided by ebuild
libc = "*"
poll_token_derive = { version = "*", path = "poll_token_derive" }
sync = { path = "../sync" } # provided by ebuild
syscall_defines = { path = "../syscall_defines" } # provided by ebuild

[workspace]
