homepage: "http://llvm.org/"
primary_contact: "kcc@google.com"
auto_ccs:
  - "mascasa@google.com"
  - "jdevlieghere@apple.com"
  - "vsk@apple.com"
  - "akilsrin@apple.com"
  - "llvm-bugs@lists.llvm.org"
  - "igmyrj@gmail.com"
  - "mitchphillips@outlook.com"
  - "mitchp@google.com"
  - "xpl0re@gmail.com"
  - "jfb@chromium.org"
  - "eneyman@google.com"
  - "bigcheesegs@gmail.com"
  - "davg@google.com"

sanitizers:
  - address
  - memory

# The LLVM build currently supports only libFuzzer
fuzzing_engines:
    - libfuzzer

# Bug reports are public by default:
view_restrictions: none
