{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.4.0-alpha01.aar",
          "url": "navigation-runtime-ktx-2.4.0-alpha01.aar",
          "size": 13237,
          "sha512": "cbd66a95e5b4805aa19b4bcf1059d7371d5e67d141a6bab26fc5f286d80cdb5e680408ff8dee1d1adbf9a344c62bb8879ecf204bfd31dba54130d850625aef73",
          "sha256": "4ba00d34011ce750cf12d4c66997ebf95ee283f78041962af3b8a9fe13d11f44",
          "sha1": "b42344e1fddc521d956ae641d289cbb1499393f6",
          "md5": "795bba4439d55cc6c91f95a6fc16a80b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.4.0-alpha01.aar",
          "url": "navigation-runtime-ktx-2.4.0-alpha01.aar",
          "size": 13237,
          "sha512": "cbd66a95e5b4805aa19b4bcf1059d7371d5e67d141a6bab26fc5f286d80cdb5e680408ff8dee1d1adbf9a344c62bb8879ecf204bfd31dba54130d850625aef73",
          "sha256": "4ba00d34011ce750cf12d4c66997ebf95ee283f78041962af3b8a9fe13d11f44",
          "sha1": "b42344e1fddc521d956ae641d289cbb1499393f6",
          "md5": "795bba4439d55cc6c91f95a6fc16a80b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.4.0-alpha01-sources.jar",
          "url": "navigation-runtime-ktx-2.4.0-alpha01-sources.jar",
          "size": 6128,
          "sha512": "f976814e20f825b4f16bf017c59918c3eb42304e8cb934b491431d2cf1e280bceea3a63b255a8ebbfcbb3886fdf26bd2a258e41928747b90eb04075e421ef4df",
          "sha256": "17df0a9cfd3b645ce58d9716f293ffdcfd8f30b60b87dab2a3cf099dddc1e70a",
          "sha1": "4d2da12a557444e5706dd6ca99f059ec099a45de",
          "md5": "fe0b36da8a72a76b3f3e34d30eebbcb2"
        }
      ]
    }
  ]
}
