{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-migration",
    "version": "2.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "room-migration-2.3.0-alpha02.jar",
          "url": "room-migration-2.3.0-alpha02.jar",
          "size": 22274,
          "sha512": "4182bbc9662af4947336a34b917d788b72c2732b168167c7a0ee4cbf70624fbb3ea4e078ea282c32362476e9ce783e966b766cf2ee449487765fe085283817b0",
          "sha256": "fee2a8a87c22e82e4154e63b7b57939ebc3ed03ba27cf95d64f8235e19e6f17c",
          "sha1": "dbc91fbdfe48e4fb264d95c88a808ca7a3e5dacd",
          "md5": "35f1eb651c2e675ab7f11608ed6a5abe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-migration-2.3.0-alpha02.jar",
          "url": "room-migration-2.3.0-alpha02.jar",
          "size": 22274,
          "sha512": "4182bbc9662af4947336a34b917d788b72c2732b168167c7a0ee4cbf70624fbb3ea4e078ea282c32362476e9ce783e966b766cf2ee449487765fe085283817b0",
          "sha256": "fee2a8a87c22e82e4154e63b7b57939ebc3ed03ba27cf95d64f8235e19e6f17c",
          "sha1": "dbc91fbdfe48e4fb264d95c88a808ca7a3e5dacd",
          "md5": "35f1eb651c2e675ab7f11608ed6a5abe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-migration-2.3.0-alpha02-sources.jar",
          "url": "room-migration-2.3.0-alpha02-sources.jar",
          "size": 17519,
          "sha512": "960387fc59572bd9762b8a359db16166fd1f5821d4d4d76bfe5621e2f13edf5fc6b1cced3bbab8f2aeb0fbd83c480c873620f1b9cff7dfb3be514d5bf9f19bdf",
          "sha256": "71105c4652819e0903cb4f073d7f51ca571e454dc5babba869e70ac4feb20180",
          "sha1": "5ad2842e154cf057d707cdbbb48055112b6ea626",
          "md5": "d79147c8aef13b99521281bb59267642"
        }
      ]
    }
  ]
}
