homepage: "http://libcxxabi.llvm.org/"
primary_contact: "kcc@google.com"
auto_ccs:
  - "Erik.Pilkington@gmail.com"
  - "akilsrin@apple.com"
  - "bigcheesegs@gmail.com"
  - "eric@efcs.ca"
sanitizers:
  - address
  - memory
  - undefined
