homepage: https://android.googlesource.com/platform/external/aac/
primary_contact: audio-fdk@iis.fraunhofer.de
auto_ccs:
  - jmtrivi@google.com
vendor_ccs:
  - bcreasey@google.com
  - hamzeh@google.com
  - geuteneier@google.com
  - hollyhall@google.com
  - mikelogan@google.com
architectures:
  - x86_64
  - i386
