version: 2.7build{build}
clone_depth: 5
branches:
  only:
    - master
    - /\d\.\d/
    - buildbot-custom
cache:
  - externals -> PCbuild\*
before_build:
  - ps: |+
      if ($env:APPVEYOR_RE_BUILD) {
        echo 'Doing full build due to re-build request.'
      } elseif (!$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT) {
        echo 'Not a PR, doing full build.'
      } else {
        git fetch -q origin +refs/heads/$env:APPVEYOR_REPO_BRANCH
        $mergebase = git merge-base HEAD FETCH_HEAD
        $changes = git diff --name-only HEAD $mergebase | grep -vE '(\.rst$)|(^Doc)|(^Misc)'
        If (!$changes) {
          echo 'Only docs were updated, stopping build process.'
          Exit-AppveyorBuild
        } else {
          echo 'Doing full build due to non-doc changes in these files:'
          echo $changes
        }
      }


build_script:
  - cmd: PCbuild\build.bat -e
  - cmd: PCbuild\python.exe -m test.pythoninfo
test_script:
  - cmd: PCbuild\rt.bat -q -uall -u-cpu -u-largefile -rwW --slowest -j2
environment:
  HOST_PYTHON: C:\Python36\python.exe
