homepage: "https://cppcheck.sourceforge.net"
primary_contact: "daniel.marjamaki@gmail.com"
auto_ccs:
  - "daniel.marjamaki@gmail.com"
  - "ettl.martin78@gmail.com"
sanitizers:
  - address
  - undefined
