homepage: "https://github.com/google/go-attestation"
primary_contact: "bweeks@google.com"
auto_ccs:
  - "ericchiang@google.com"
  - "jsonp@google.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
language: go
