#! /bin/bash
#
# Copyright 2019 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage() {
  cat >&2 <<EOF
Determine the 32- or 64-bit architecture of a device and print the path to
native libraries installed on the device for testing purposes.

Usage:
  $0 --32    Select the 32-bit architecture
  $0 --64    Select the 64-bit architecture
EOF
  exit 1
}

if [[ $# -ne 1 ]]; then
  usage
fi

case "$1" in
  (--32) TEST_DIRECTORY="nativetest";;
  (--64) TEST_DIRECTORY="nativetest64";;
  (*) usage;;
esac

if [[ -z "$ANDROID_BUILD_TOP" ]]; then
  echo 'ANDROID_BUILD_TOP environment variable is empty; did you forget to run `lunch`?'
  exit 1
fi

bitness_flag=$1
ISA=$("$ANDROID_BUILD_TOP/art/test/utils/get-device-isa" "$bitness_flag")

echo "/data/${TEST_DIRECTORY}/art/${ISA}"
