dist: "trusty"
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
  - "pypy3"
install: 
  - "if python --version 2>&1 | grep -q ' 2\.7\.'; then pip install flake8 ; fi"
script:
  - "make test"
  - "make lint-if-2.7"
notifications:
  email:
    - phihag@phihag.de
sudo: false
