homepage: "https://github.com/GNUAspell/aspell"
primary_contact: "kevina@gnu.org"
auto_ccs:
  - "kevinatkn@gmail.com"
  - "cmeister2@gmail.com"
sanitizers:
  - address
  - undefined
  - memory:
      experimental: true
