homepage: "https://www.djangoproject.com/"
primary_contact: "guidovranken@gmail.com"
auto_ccs:
 - "f.apolloner@gmail.com"
 - "info+django+security@markusholtermann.eu"
 - "jammamarkus@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
 - undefined
