{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-alpha05.aar",
          "url": "lifecycle-livedata-2.3.0-alpha05.aar",
          "size": 10205,
          "sha512": "455471b319e9916b6d172c12e18a8251f543bc0ce5ee24e3b1370aebfb6d29c9f4c813bb679643ab272b1486be0e54c06a02beea5d4af668b1a359adb4217749",
          "sha256": "946f82b64f74091abfe41858cd6883c3afe3ba8602b7d6576edf85856d005e41",
          "sha1": "f40170f9bdcf769b7304496a6423654c2854fb3b",
          "md5": "6b4668bd4d3bc4136d96263aace91ec6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-alpha05.aar",
          "url": "lifecycle-livedata-2.3.0-alpha05.aar",
          "size": 10205,
          "sha512": "455471b319e9916b6d172c12e18a8251f543bc0ce5ee24e3b1370aebfb6d29c9f4c813bb679643ab272b1486be0e54c06a02beea5d4af668b1a359adb4217749",
          "sha256": "946f82b64f74091abfe41858cd6883c3afe3ba8602b7d6576edf85856d005e41",
          "sha1": "f40170f9bdcf769b7304496a6423654c2854fb3b",
          "md5": "6b4668bd4d3bc4136d96263aace91ec6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.3.0-alpha05-sources.jar",
          "url": "lifecycle-livedata-2.3.0-alpha05-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
