{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.2.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha05"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.2.0-alpha07.aar",
          "url": "activity-ktx-1.2.0-alpha07.aar",
          "size": 15551,
          "sha512": "2651b6a9aff8831ce06655751831bb5a1fac6c2cd76eb6d6774761100904931367b6b18480275b849f7440af2356098406df0485eeffc55f68b02195729b7cba",
          "sha256": "05a05ca915e11b41afd9e9b801a758ebc1cc4a73c1a667487a0c96be4529711d",
          "sha1": "9d36d0c976c369c2364251578e08f0d7adf1fd23",
          "md5": "3126903c6dd5a883d3f0f8aabf33026f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha05"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.2.0-alpha07.aar",
          "url": "activity-ktx-1.2.0-alpha07.aar",
          "size": 15551,
          "sha512": "2651b6a9aff8831ce06655751831bb5a1fac6c2cd76eb6d6774761100904931367b6b18480275b849f7440af2356098406df0485eeffc55f68b02195729b7cba",
          "sha256": "05a05ca915e11b41afd9e9b801a758ebc1cc4a73c1a667487a0c96be4529711d",
          "sha1": "9d36d0c976c369c2364251578e08f0d7adf1fd23",
          "md5": "3126903c6dd5a883d3f0f8aabf33026f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.2.0-alpha07-sources.jar",
          "url": "activity-ktx-1.2.0-alpha07-sources.jar",
          "size": 4962,
          "sha512": "e76ce421229268e23fc4b6e4c9bbd7bd56437f64c848cb1e918a694cdc37590c78f9bd4e9199c48d6747f30da5d8662a02738c0ed017a6c40a772f9832dc9368",
          "sha256": "5226aa053cb21109e845fe75c0a4e743a3fa74fad79fadc0aa47399b6b4992ff",
          "sha1": "46779e794d5fa3d241bd54602f058ef01bd75f20",
          "md5": "15faec8edd1a9372062c7331ee5c8d4a"
        }
      ]
    }
  ]
}
