{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.3.0-alpha07.aar",
          "url": "fragment-1.3.0-alpha07.aar",
          "size": 277035,
          "sha512": "a2ca1a14ce5930f0e0dc8c0108f46365dae05940e102a1ce7d14ab91f59697f923d0c1e55f2364545d23498d5fc5ed8e6c873c475cc2dd02a8cd57ea1ae3dc18",
          "sha256": "0f327d8e657484a5a77f4ca9b9e7bfb6865125921aa0a0a2a9e6c9f812cb815a",
          "sha1": "9434385b1ab88a4d45be1334bfda9f96ea4c4ffd",
          "md5": "e68ff17acdae5d2227c75a8bcf6b6f99"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0-alpha05"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.3.0-alpha07.aar",
          "url": "fragment-1.3.0-alpha07.aar",
          "size": 277035,
          "sha512": "a2ca1a14ce5930f0e0dc8c0108f46365dae05940e102a1ce7d14ab91f59697f923d0c1e55f2364545d23498d5fc5ed8e6c873c475cc2dd02a8cd57ea1ae3dc18",
          "sha256": "0f327d8e657484a5a77f4ca9b9e7bfb6865125921aa0a0a2a9e6c9f812cb815a",
          "sha1": "9434385b1ab88a4d45be1334bfda9f96ea4c4ffd",
          "md5": "e68ff17acdae5d2227c75a8bcf6b6f99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-1.3.0-alpha07-sources.jar",
          "url": "fragment-1.3.0-alpha07-sources.jar",
          "size": 174515,
          "sha512": "88c8382dffb4b4a4400fe760b14bf0561b8d4b9deb32df7aac113e6e072c8eb69bc417d1f8a1468226c2662ea7f6fe6e8aabae51d623b63ca7ada5302f6d9a22",
          "sha256": "dcdf8265e383d3fad1b73d0c4144f79d9e1592be53cc9da2c25d1399ef163442",
          "sha1": "90cc443c712e3073f8c86084fa36778bf10c9875",
          "md5": "8a7bffdd6a53e86fcd25e03901cc0f80"
        }
      ]
    }
  ]
}
