{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.3.0-alpha01.aar",
          "url": "appcompat-resources-1.3.0-alpha01.aar",
          "size": 61738,
          "sha512": "2fe9e98fd16443a1ca7cab23fd872db7d1507f481a0404c03f46f64d7c4d34226bd1058ef4a3cc32a34cbfef28f4802dbf835c260277e4572522d5c9e768ea36",
          "sha256": "e0aeb12700a51e336580c1d053694f35dfd64c619132ba94532dbbce688df2c2",
          "sha1": "28dbb88b3a5493ce55b4e3311b72204b93a8b884",
          "md5": "9a2debc5390cebba3e88c98bb11f24a6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.3.0-alpha01.aar",
          "url": "appcompat-resources-1.3.0-alpha01.aar",
          "size": 61738,
          "sha512": "2fe9e98fd16443a1ca7cab23fd872db7d1507f481a0404c03f46f64d7c4d34226bd1058ef4a3cc32a34cbfef28f4802dbf835c260277e4572522d5c9e768ea36",
          "sha256": "e0aeb12700a51e336580c1d053694f35dfd64c619132ba94532dbbce688df2c2",
          "sha1": "28dbb88b3a5493ce55b4e3311b72204b93a8b884",
          "md5": "9a2debc5390cebba3e88c98bb11f24a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.3.0-alpha01-sources.jar",
          "url": "appcompat-resources-1.3.0-alpha01-sources.jar",
          "size": 38423,
          "sha512": "b0fb4f1a26f49e0679b13dc78f51af7b68d221107d580a311ebb6fb6a1ff959e2c4327b0c95be9288d20f44d67f47f9a9cb252a210d4cf3dfff85d7e716061c1",
          "sha256": "ac712f6c0661535fb7aace52804fe4520d49a2d6a8e8409b6836f8404d5f26e4",
          "sha1": "24f173365f01627889533d5931fd5e8a26be6c21",
          "md5": "8e3e21c5c4e6d80a6587879628a3c8b3"
        }
      ]
    }
  ]
}
