{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler",
    "version": "2.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "room-compiler-2.3.0-alpha02.jar",
          "url": "room-compiler-2.3.0-alpha02.jar",
          "size": 3621035,
          "sha512": "19d38800f777b358e861fb80f204ba75405e261275c13f448cc95ce77a2dd924d5405d04745a58eaad65d5776ed7f7f30ddaeb066ed940f4dba9e5f035bd07c7",
          "sha256": "4f7792842ffb4453593030a2865af25c322b1e73ac93d8c886bea109d7fa4529",
          "sha1": "e212ac3009eb4967febda0f31fea815450eede83",
          "md5": "1ffa0423a58eb772b4ec22e967ad6e92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.25.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.3.0-alpha02.jar",
          "url": "room-compiler-2.3.0-alpha02.jar",
          "size": 3621035,
          "sha512": "19d38800f777b358e861fb80f204ba75405e261275c13f448cc95ce77a2dd924d5405d04745a58eaad65d5776ed7f7f30ddaeb066ed940f4dba9e5f035bd07c7",
          "sha256": "4f7792842ffb4453593030a2865af25c322b1e73ac93d8c886bea109d7fa4529",
          "sha1": "e212ac3009eb4967febda0f31fea815450eede83",
          "md5": "1ffa0423a58eb772b4ec22e967ad6e92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-2.3.0-alpha02-sources.jar",
          "url": "room-compiler-2.3.0-alpha02-sources.jar",
          "size": 402233,
          "sha512": "4e391e48ae0f102e1253692d90a110c4bc307f76cfb6eeabb5da47c115391c62a82001ee782129bca19b094bdefaf9553b018f44a12d5fa709aed1c89d2d246e",
          "sha256": "ea6ee599ae4f18b7989ec4249307c2ba0f39de60346e2aea4531c366d2e814c6",
          "sha1": "5d8f7bd6d97298cf68488b4a98f3c98005f5eda6",
          "md5": "f8c68fda669b5ef7729e88e5b7ade105"
        }
      ]
    }
  ]
}
