homepage: "https://github.com/google/wuffs"
primary_contact: "nigeltao@golang.org"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - undefined
  - dataflow
architectures:
  - x86_64
  - i386
