homepage: "http://facebook.github.io/zstd/"
primary_contact: "terrelln@fb.com"
auto_ccs:
  - "NickRTerrell@gmail.com"
  - "Yann.collet.73@gmail.com"
  - "cyan@fb.com"
  - "felixh@fb.com"
  - "dpc@fb.com"
  - "bimbashrestha@fb.com"
  - "mhl@fb.com"
  - "reed@fb.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
  - honggfuzz
sanitizers:
  - address
  - dataflow
  - memory
  - undefined
