homepage: "https://libcxx.llvm.org/"
primary_contact: "mclow.lists@gmail.com"
auto_ccs:
  - "timshen91@gmail.com"
  - "jfb@chromium.org"
  - "bigcheesegs@gmail.com"
  - "eric@efcs.ca"
  - "ldionne.2@gmail.com"
