{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.autofill",
    "module": "autofill",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autofill-1.1.0-alpha02.aar",
          "url": "autofill-1.1.0-alpha02.aar",
          "size": 36046,
          "sha512": "59c6175461d1b0a8927a034bc05f17891ae7e97c6938d4a2a299e00825ec53be9392e7f7d1d1919dd65336b0a2f847857df3a480af178cf40a4601c6e7d02483",
          "sha256": "b013af5ad02ab6d82899d5eace0c303e3658fb53cc1cba48d362175c08d9e15b",
          "sha1": "b6e256a79e378ac75fd172e1f9b542d428372279",
          "md5": "c7084b1747f908b39d3c460b928b8f82"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "autofill-1.1.0-alpha02.aar",
          "url": "autofill-1.1.0-alpha02.aar",
          "size": 36046,
          "sha512": "59c6175461d1b0a8927a034bc05f17891ae7e97c6938d4a2a299e00825ec53be9392e7f7d1d1919dd65336b0a2f847857df3a480af178cf40a4601c6e7d02483",
          "sha256": "b013af5ad02ab6d82899d5eace0c303e3658fb53cc1cba48d362175c08d9e15b",
          "sha1": "b6e256a79e378ac75fd172e1f9b542d428372279",
          "md5": "c7084b1747f908b39d3c460b928b8f82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autofill-1.1.0-alpha02-sources.jar",
          "url": "autofill-1.1.0-alpha02-sources.jar",
          "size": 24656,
          "sha512": "6dd416831bdcd554ddd1242a5d1ee9619a5fbaf11a1c61fb6c33fb4cc2834d5c68c5876d8aa8ac662fec72c03fc534379a3752b920514f097ed25a04cb3747de",
          "sha256": "c994b3e3ebe873a9044b55d1927c0c3f61bce9362fc519c1a93f92fcb041c2a6",
          "sha1": "f0cc512787fa562a618dcfa02ffffa423be1f260",
          "md5": "49cf7abff84e94edbaaf47081184da62"
        }
      ]
    }
  ]
}
