{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media2",
    "module": "media2-exoplayer",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media2-exoplayer-1.1.0-alpha01.aar",
          "url": "media2-exoplayer-1.1.0-alpha01.aar",
          "size": 1340779,
          "sha512": "88e30fb11e6ba6ed75f29bb6ae2e0c3a776ff09288c14140dddfd7cf4d5e26b2be06e0480e900a276b52c41791ff658bfbbc54ec7f13b9b65050c82428a3c46c",
          "sha256": "fe98540d62761117de2c35c5ed49b27c448a99c4d62cbef765802bc69cd0ad67",
          "sha1": "16acdadf0df77add9244f9d2aa4dff82a2d26095",
          "md5": "e9c6852e3e05a31e37d5a6080cf21784"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media2-exoplayer-1.1.0-alpha01.aar",
          "url": "media2-exoplayer-1.1.0-alpha01.aar",
          "size": 1340779,
          "sha512": "88e30fb11e6ba6ed75f29bb6ae2e0c3a776ff09288c14140dddfd7cf4d5e26b2be06e0480e900a276b52c41791ff658bfbbc54ec7f13b9b65050c82428a3c46c",
          "sha256": "fe98540d62761117de2c35c5ed49b27c448a99c4d62cbef765802bc69cd0ad67",
          "sha1": "16acdadf0df77add9244f9d2aa4dff82a2d26095",
          "md5": "e9c6852e3e05a31e37d5a6080cf21784"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media2-exoplayer-1.1.0-alpha01-sources.jar",
          "url": "media2-exoplayer-1.1.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
