language: java

sudo: false

env:
  global:
    secure: "bEwUUf3355VeqQZYTO0wsZKogquTUNwPQIwKWyHTGGaEVayTwfF2sMEzWojgDPA7E6EbWmSKSm0RKFpkpu5nWr7NvnaoJa/+BpRL/69Y5qB29qVNrCyWM2ZLaoEcTxrqeLKm1ma8TA7IOLAQnxEMZYar/siV9ycDOptp2ZzUoIM="

addons:
  coverity_scan:
    project:
      name: "c-rack/cbor-java"
      description: "Build submitted via Travis CI"
    notification_email: constantin@rack.li
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: master

