homepage: "http://www.leptonica.com"
primary_contact: "taking@google.com"
auto_ccs:
  - "kusano@google.com"
  - "dbloomberg@google.com"
  - "stjoweil@googlemail.com"
sanitizers:
  - address
  - undefined
  - memory
labels:
  pix_rotate_shear_fuzzer:
    - sundew
