{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.collection",
    "module": "collection-ktx",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6616358"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha01.jar",
          "url": "collection-ktx-1.2.0-alpha01.jar",
          "size": 18877,
          "sha512": "f4be51b004e9bc8a69e07bd40829663862eb23fa347fda171da74937e05dbf5013bd104aca5c866346470a57a681348388df1b12762c92ad217c721eb2ab4e23",
          "sha256": "8dc030f501e6e4d06c6073f70e55beda69c7f0d6e9b92044cdc39164ed5883ae",
          "sha1": "c79cf0f974a6a906cf8c7bf66efb42305de315a9",
          "md5": "e19966786c4989ad7ffc6627a3706d77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha01.jar",
          "url": "collection-ktx-1.2.0-alpha01.jar",
          "size": 18877,
          "sha512": "f4be51b004e9bc8a69e07bd40829663862eb23fa347fda171da74937e05dbf5013bd104aca5c866346470a57a681348388df1b12762c92ad217c721eb2ab4e23",
          "sha256": "8dc030f501e6e4d06c6073f70e55beda69c7f0d6e9b92044cdc39164ed5883ae",
          "sha1": "c79cf0f974a6a906cf8c7bf66efb42305de315a9",
          "md5": "e19966786c4989ad7ffc6627a3706d77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha01-sources.jar",
          "url": "collection-ktx-1.2.0-alpha01-sources.jar",
          "size": 5947,
          "sha512": "7ebe8f7fb6c8d1b9247d07e3722540ca6535715c98c25af2dfb91e52ff6a3b500f3de5db34112203201d412703e136b9c568dd3c53e32df56e02f2391a0c0712",
          "sha256": "906a9d5a2cdf2f14813f597a573d0a1ccc6b0e42a2ee398208694fcead68dd08",
          "sha1": "7d7f3841485f3dc438d8b1f243c385a86ac34f90",
          "md5": "935054299ef8169fa22bc89312c4ec6b"
        }
      ]
    }
  ]
}
