#
# Power Test TCM Nanoapp Makefile
#

# Nanoapp Configuration ########################################################

NANOAPP_NAME = power_test_tcm
NANOAPP_ID = 0x0123456789000010
NANOAPP_NAME_STRING = \"Power\ Test\ TCM\"

# Common Compiler Flags ########################################################

COMMON_CFLAGS += -DCHRE_TCM_BUILD

# Makefile Includes ############################################################

include ../common/power_test.mk