#!/bin/bash
#
# Copyright 2019 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop on failure.
set -e

# Deref the symlink.
mv src-ex/java/util/AbstractCollection.java src-ex/java/util/AbstractCollection.bak
cp src-ex/java/util/AbstractCollection.bak src-ex/java/util/AbstractCollection.java

# Patch the copied version.
patch src-ex/java/util/AbstractCollection.java AbstractCollection.patch

DESUGAR=false ./default-build "$@"

# restore the symlink
rm src-ex/java/util/AbstractCollection.java
mv src-ex/java/util/AbstractCollection.bak src-ex/java/util/AbstractCollection.java
