id: 8835981461554930288
count_metric {
  id: 543749824321007836
  what: 3909523419673092535
  dimensions_in_what {
    field: 99
    child {
      field: 1
    },
    child {
      field: 2
    },
    child {
      field: 3
    }
  }
  bucket: ONE_DAY
}
atom_matcher {
  id: 3909523419673092535
  simple_atom_matcher {
    atom_id: 99
    field_value_matcher: {
      eq_int: 1
      field: 4
    }
  }
}
allowed_log_source: "AID_GRAPHICS"
allowed_log_source: "AID_INCIDENTD"
allowed_log_source: "AID_STATSD"
allowed_log_source: "AID_RADIO"
allowed_log_source: "com.android.systemui"
allowed_log_source: "com.android.vending"
allowed_log_source: "AID_SYSTEM"
allowed_log_source: "AID_ROOT"
allowed_log_source: "AID_BLUETOOTH"
default_pull_packages: "AID_SYSTEM"

hash_strings_in_metric_report: false
