homepage: "https://github.com/sctplab/usrsctp"
primary_contact: "weinrank@fh-muenster.de"
auto_ccs:
  - "t00fcxen@googlemail.com"
  - "markwo@google.com"
sanitizers:
  - address
  - memory
  - undefined
