#
# Power Test Nanoapp Makefile
#

# Nanoapp Configuration ########################################################

NANOAPP_NAME = power_test
NANOAPP_ID = 0x012345678900000f
NANOAPP_NAME_STRING = \"Power\ Test\"

# Makefile Includes ############################################################

include ../common/power_test.mk
